spring.application.name=Skill8
spring.datasource.url=jdbc:mysql://localhost:3306/Skill8db
spring.datasource.username=root
spring.datasource.password=10_Laxmi@Sahithi_30

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080