spring.application.name=Skill7
# Server configuration
server.port=8083

# Disable database auto configuration (since we are using in-memory List)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Optional: show logs clearly
spring.main.banner-mode=console
logging.level.org.springframework=INFO